name: TOC generator

on:
  push:
  pull_request:

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/toc-generator@v4
        with:
              TOC_TITLE: "## Contents"